### 2021_10_19_3 4

In [100]:
import pandas as pd

### 데이터 불러오기

In [101]:
train = pd.read_csv("../CSV/spotify_dataset.csv")

In [102]:
train.columns

Index(['Index', 'Highest Charting Position', 'Number of Times Charted',
       'Week of Highest Charting', 'Song Name', 'Streams', 'Artist',
       'Artist Followers', 'Song ID', 'Genre', 'Release Date', 'Weeks Charted',
       'Popularity', 'Danceability', 'Energy', 'Loudness', 'Speechiness',
       'Acousticness', 'Liveness', 'Tempo', 'Duration (ms)', 'Valence',
       'Chord'],
      dtype='object')

In [103]:
train.head(3)

,Index,Highest Charting Position,Number of Times Charted,Week of Highest Charting,Song Name,Streams,Artist,Artist Followers,Song ID,Genre,...,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence,Chord
0,1,1,8,2021-07-23--2021-07-30,Beggin',"48,633,449",Måneskin,3377762,3Wrjm47oTz2sjIgck11l5e,"['indie rock italiano', 'italian pop']",...,0.714,0.8,-4.808,0.0504,0.127,0.359,134.002,211560,0.589,B
1,2,2,3,2021-07-23--2021-07-30,STAY (with Justin Bieber),"47,248,719",The Kid LAROI,2230022,5HCyWlXZPP0y6Gqq8TgA20,['australian hip hop'],...,0.591,0.764,-5.484,0.0483,0.0383,0.103,169.928,141806,0.478,C#/Db
2,3,1,11,2021-06-25--2021-07-02,good 4 u,"40,162,559",Olivia Rodrigo,6266514,4ZtFanR9U6ndgddUvNcjcG,['pop'],...,0.563,0.664,-5.044,0.154,0.335,0.0849,166.928,178147,0.688,A

In [104]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Index                      1556 non-null   int64
 1   Highest Charting Position  1556 non-null   int64
 2   Number of Times Charted    1556 non-null   int64
 3   Week of Highest Charting   1556 non-null   object
 4   Song Name                  1556 non-null   object
 5   Streams                    1556 non-null   object
 6   Artist                     1556 non-null   object
 7   Artist Followers           1556 non-null   object
 8   Song ID                    1556 non-null   object
 9   Genre                      1556 non-null   object
 10  Release Date               1556 non-null   object
 11  Weeks Charted              1556 non-null   object
 12  Popularity                 1556 non-null   object
 13  Danceability               1556 non-null   object
 14  Energy                     1556 non-null   object
 15  Loudness                   1556 non-null   object
 16  Speechiness                1556 non-null   object
 17  Acousticness               1556 non-null   object
 18  Liveness                   1556 non-null   object
 19  Tempo                      1556 non-null   object
 20  Duration (ms)              1556 non-null   object
 21  Valence                    1556 non-null   object
 22  Chord                      1556 non-null   object
dtypes: int64(3), object(20)
memory usage: 279.7+ KB

### 데이터 전처리
* 결측치 제거
    * " " -> "0"으로 변경
* 불필요 기호 제거
    * ","제거
* 데이터 타입 변경
    * object -> int or float

In [105]:
train.loc[train["Artist Followers"] == " ", "Artist Followers"] = "0"
train["Artist Followers"] = train["Artist Followers"].astype(int)

train["Streams"] = train["Streams"].replace(r",", "", regex = True)
train["Streams"] = train["Streams"].astype(int)

train.loc[train["Popularity"] == " ", "Popularity"] = "0"
train["Popularity"] = train["Popularity"].astype(int)

train.loc[train["Tempo"] == " ", "Tempo"] = "0"
train["Tempo"] = train["Tempo"].astype(float)
train.loc[train["Danceability"] == " ", "Danceability"] = "0"
train["Danceability"] = train["Danceability"].astype(float)
train.loc[train["Energy"] == " ", "Energy"] = "0"
train["Energy"] = train["Energy"].astype(float)

In [106]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Index                      1556 non-null   int64
 1   Highest Charting Position  1556 non-null   int64
 2   Number of Times Charted    1556 non-null   int64
 3   Week of Highest Charting   1556 non-null   object
 4   Song Name                  1556 non-null   object
 5   Streams                    1556 non-null   int64
 6   Artist                     1556 non-null   object
 7   Artist Followers           1556 non-null   int64
 8   Song ID                    1556 non-null   object
 9   Genre                      1556 non-null   object
 10  Release Date               1556 non-null   object
 11  Weeks Charted              1556 non-null   object
 12  Popularity                 1556 non-null   int64
 13  Danceability               1556 non-null   float64
 14  Energy                     1556 non-null   float64
 15  Loudness                   1556 non-null   object
 16  Speechiness                1556 non-null   object
 17  Acousticness               1556 non-null   object
 18  Liveness                   1556 non-null   object
 19  Tempo                      1556 non-null   float64
 20  Duration (ms)              1556 non-null   object
 21  Valence                    1556 non-null   object
 22  Chord                      1556 non-null   object
dtypes: float64(3), int64(6), object(14)
memory usage: 279.7+ KB

In [107]:
train.head(3)

,Index,Highest Charting Position,Number of Times Charted,Week of Highest Charting,Song Name,Streams,Artist,Artist Followers,Song ID,Genre,...,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence,Chord
0,1,1,8,2021-07-23--2021-07-30,Beggin',48633449,Måneskin,3377762,3Wrjm47oTz2sjIgck11l5e,"['indie rock italiano', 'italian pop']",...,0.714,0.800,-4.808,0.0504,0.127,0.359,134.002,211560,0.589,B
1,2,2,3,2021-07-23--2021-07-30,STAY (with Justin Bieber),47248719,The Kid LAROI,2230022,5HCyWlXZPP0y6Gqq8TgA20,['australian hip hop'],...,0.591,0.764,-5.484,0.0483,0.0383,0.103,169.928,141806,0.478,C#/Db
2,3,1,11,2021-06-25--2021-07-02,good 4 u,40162559,Olivia Rodrigo,6266514,4ZtFanR9U6ndgddUvNcjcG,['pop'],...,0.563,0.664,-5.044,0.154,0.335,0.0849,166.928,178147,0.688,A

In [51]:
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
import numpy as np

### LogisticRegression

In [108]:
X = train[["Number of Times Charted", "Streams", 
           "Artist Followers", "Popularity"]]
y = train["Highest Charting Position"]

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   test_size = 0.2,
                                                   random_state = 42)

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
pred = logreg.predict(X_test)

/Users/seungwoomun/opt/anaconda3/envs/likelion/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [109]:
dict_dat = {"실제값" : y_test, "예측값" : pred, "오차" : y_test - pred}
dat = pd.DataFrame(dict_dat)
dat.head(10)

      실제값  예측값   오차
1496   91    1   90
168     1    2   -1
353   195    1  194
468     3    2    1
1410   96    1   95
1509  168    1  167
59     31    1   30
415    19    1   18
715   104    4  100
354    64    1   63

### LinearRegression

In [110]:
for i in range(1, 6, 1) :
    X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                       test_size = (i / 10),
                                                       random_state = 42)
    model = LinearRegression().fit(X_train, y_train)
    pred = model.predict(X_test)
    
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)
    
    mae_val = np.abs(y_test - pred).sum() / len(pred)
    mse_val = ((y_test - pred) ** 2).sum() / len(pred)
    rmse_val = mse_val ** 0.5
    
    print(f"학습용 : {10 - i}, 테스트용 : {i}")
    print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
    print("MAE : {}".format(mae_val))
    print("MSE : {}".format(mse_val))
    print("RMSE : {}".format(rmse_val))
    print()
    
dict_dat = {"실제값" : y_test, "예측값" : pred, "오차" : y_test - pred}
dat = pd.DataFrame(dict_dat)
dat.head(10)

학습용 : 9, 테스트용 : 1
학습용 : 0.3095808703643923, 테스트용 : 0.3453737518653427
MAE : 37.28093373647653
MSE : 2037.9781263928091
RMSE : 45.143971096845355

학습용 : 8, 테스트용 : 2
학습용 : 0.314631677189799, 테스트용 : 0.30225419605470083
MAE : 39.684149868105095
MSE : 2273.2761213968133
RMSE : 47.678885488199214

학습용 : 7, 테스트용 : 3
학습용 : 0.313952141098399, 테스트용 : 0.30787043603186204
MAE : 40.42529788517363
MSE : 2308.7867127559934
RMSE : 48.049835720385076

학습용 : 6, 테스트용 : 4
학습용 : 0.31456788293665516, 테스트용 : 0.3074766557732853
MAE : 40.523751231712765
MSE : 2320.2693813030764
RMSE : 48.169174596447846

학습용 : 5, 테스트용 : 5
학습용 : 0.31522791636320024, 테스트용 : 0.3093833688095933
MAE : 40.946126400415494
MSE : 2355.8287084892318
RMSE : 48.53687988003794

      실제값         예측값         오차
1496   91   99.600020  -8.600020
168     1   29.961934 -28.961934
353   195  119.779232  75.220768
468     3    5.941991  -2.941991
1410   96  106.356837 -10.356837
1509  168  116.207666  51.792334
59     31   70.780112 -39.780112
415    19   18.072927   0.927073
715   104   82.179547  21.820453
354    64  103.646265 -39.646265

In [111]:
X = train[["Number of Times Charted", "Streams", 
           "Artist Followers", "Popularity"]]
y = train["Highest Charting Position"]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size = (1 / 10),
                                                   random_state = 42)
model = LinearRegression().fit(X_train, y_train)
pred = model.predict(X_test)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

mae_val = np.abs(y_test - pred).sum() / len(pred)
mse_val = ((y_test - pred) ** 2).sum() / len(pred)
rmse_val = mse_val ** 0.5

print(f"학습용 : {10 - 1}, 테스트용 : {1}")
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
print("MAE : {}".format(mae_val))
print("MSE : {}".format(mse_val))
print("RMSE : {}".format(rmse_val))
print()
    
dict_dat = {"실제값" : y_test, "예측값" : pred, "오차" : y_test - pred}
dat = pd.DataFrame(dict_dat)
dat.head(10)

학습용 : 9, 테스트용 : 1
학습용 : 0.3095808703643923, 테스트용 : 0.3453737518653427
MAE : 37.28093373647653
MSE : 2037.9781263928091
RMSE : 45.143971096845355

      실제값         예측값         오차
1496   91   97.948928  -6.948928
168     1   30.004586 -29.004586
353   195  118.780675  76.219325
468     3    5.924436  -2.924436
1410   96  104.975561  -8.975561
1509  168  115.013642  52.986358
59     31   69.973335 -38.973335
415    19   18.019924   0.980076
715   104   81.209234  22.790766
354    64  103.155323 -39.155323

### LinearRegression column 추가

In [112]:
X = train[["Number of Times Charted", "Streams",
           "Artist Followers", "Popularity", "Tempo", "Danceability",
          "Energy"]]
y = train["Highest Charting Position"]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size = (1 / 10),
                                                   random_state = 42)
model = LinearRegression().fit(X_train, y_train)
pred = model.predict(X_test)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

mae_val = np.abs(y_test - pred).sum() / len(pred)
mse_val = ((y_test - pred) ** 2).sum() / len(pred)
rmse_val = mse_val ** 0.5

print(f"학습용 : {10 - 1}, 테스트용 : {1}")
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
print("MAE : {}".format(mae_val))
print("MSE : {}".format(mse_val))
print("RMSE : {}".format(rmse_val))
print()
    
dict_dat = {"실제값" : y_test, "예측값" : pred, "오차" : y_test - pred}
dat = pd.DataFrame(dict_dat)
dat.head(10)

학습용 : 9, 테스트용 : 1
학습용 : 0.3118031623038354, 테스트용 : 0.34098638963080474
MAE : 37.308183973113536
MSE : 2051.636833620068
RMSE : 45.29499788740549

      실제값         예측값         오차
1496   91   92.529067  -1.529067
168     1   28.322981 -27.322981
353   195  116.234276  78.765724
468     3    6.007788  -3.007788
1410   96  106.276787 -10.276787
1509  168  115.917335  52.082665
59     31   70.055113 -39.055113
415    19   18.018880   0.981120
715   104   82.814497  21.185503
354    64  102.226171 -38.226171

### RandomForestRegressor

In [113]:
from sklearn.ensemble import RandomForestRegressor

In [114]:
for i in range(1, 6, 1) :
    X = train[["Number of Times Charted", "Streams",
               "Artist Followers", "Popularity", "Tempo", "Danceability",
              "Energy"]]
    y = train["Highest Charting Position"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                       test_size = (i / 10),
                                                       random_state = 42)
    model = RandomForestRegressor().fit(X_train, y_train)
    pred = model.predict(X_test)

    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    mae_val = np.abs(y_test - pred).sum() / len(pred)
    mse_val = ((y_test - pred) ** 2).sum() / len(pred)
    rmse_val = mse_val ** 0.5

    print(f"학습용 : {10 - i}, 테스트용 : {i}")
    print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
    print("MAE : {}".format(mae_val))
    print("MSE : {}".format(mse_val))
    print("RMSE : {}".format(rmse_val))
    print()
    
dict_dat = {"실제값" : y_test, "예측값" : pred, "오차" : y_test - pred}
dat = pd.DataFrame(dict_dat)
dat.head(10)

학습용 : 9, 테스트용 : 1
학습용 : 0.9540070738595038, 테스트용 : 0.6206961195918703
MAE : 25.27153846153846
MSE : 1180.8463435897434
RMSE : 34.363444873728

학습용 : 8, 테스트용 : 2
학습용 : 0.9546277084955174, 테스트용 : 0.6318263319324623
MAE : 26.218846153846155
MSE : 1199.520517948718
RMSE : 34.634094732628974

학습용 : 7, 테스트용 : 3
학습용 : 0.9521710522161736, 테스트용 : 0.6460731941438651
MAE : 25.617387580299784
MSE : 1180.6192788008566
RMSE : 34.36014084372846

학습용 : 6, 테스트용 : 4
학습용 : 0.9538247972411938, 테스트용 : 0.6296895004711724
MAE : 26.157800963081865
MSE : 1240.7092422150881
RMSE : 35.22370284645111

학습용 : 5, 테스트용 : 5
학습용 : 0.9521528957459303, 테스트용 : 0.636093497717509
MAE : 25.94340616966581
MSE : 1241.356414781491
RMSE : 35.23288825488894

      실제값     예측값     오차
1496   91   85.66   5.34
168     1   37.86 -36.86
353   195  176.96  18.04
468     3   22.95 -19.95
1410   96   92.66   3.34
1509  168  149.00  19.00
59     31   25.35   5.65
415    19   28.23  -9.23
715   104   82.27  21.73
354    64   83.67 -19.67

### DecisionTreeRegressor

In [115]:
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

In [116]:
X = train[["Number of Times Charted", "Streams",
               "Artist Followers", "Popularity", "Tempo", "Danceability",
              "Energy"]]
y = train["Highest Charting Position"]

for i in range(1, 6, 1) :
    X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                       test_size = (i / 10),
                                                       random_state = 42)
    model = DecisionTreeRegressor().fit(X_train, y_train)
    pred = model.predict(X_test)

    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    mae_val = np.abs(y_test - pred).sum() / len(pred)
    mse_val = ((y_test - pred) ** 2).sum() / len(pred)
    rmse_val = mse_val ** 0.5

    print(f"학습용 : {10 - i}, 테스트용 : {i}")
    print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
    print("MAE : {}".format(mae_val))
    print("MSE : {}".format(mse_val))
    print("RMSE : {}".format(rmse_val))
    print()

학습용 : 9, 테스트용 : 1
학습용 : 1.0, 테스트용 : 0.39351787671171856
MAE : 29.942307692307693
MSE : 1888.0961538461538
RMSE : 43.45222841059079

학습용 : 8, 테스트용 : 2
학습용 : 1.0, 테스트용 : 0.27873552335712837
MAE : 32.71474358974359
MSE : 2349.900641025641
RMSE : 48.475773753759114

학습용 : 7, 테스트용 : 3
학습용 : 1.0, 테스트용 : 0.4279126160424036
MAE : 30.914346895074946
MSE : 1908.353319057816
RMSE : 43.68470349055623

학습용 : 6, 테스트용 : 4
학습용 : 1.0, 테스트용 : 0.32580712734553285
MAE : 32.834670947030496
MSE : 2258.85393258427
RMSE : 47.52740191283624

학습용 : 5, 테스트용 : 5
학습용 : 1.0, 테스트용 : 0.28462772442270057
MAE : 34.62210796915167
MSE : 2440.2750642673523
RMSE : 49.399140319112355

### 교차 검증
* RandomForestRegressor

In [117]:
X = train[["Number of Times Charted", "Streams",
               "Artist Followers", "Popularity", "Tempo", "Danceability",
              "Energy"]]
y = train["Highest Charting Position"]

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                   test_size = (i / 10),
                                                   random_state = 42)
model = RandomForestRegressor().fit(X_train, y_train)
pred = model.predict(X_test)

scores = cross_val_score(model, X_train, y_train)
scores

array([0.62056753, 0.61171541, 0.67388137, 0.63003435, 0.65418071])

In [118]:
from sklearn.model_selection import KFold

In [119]:
kfold = KFold(n_splits = 5)
scores = cross_val_score(model, X_train, y_train, cv = kfold)
print("교차 검증 점수 :\n{}".format(scores))

교차 검증 점수 :
[0.63212734 0.63165196 0.67022907 0.63125016 0.65662899]

In [120]:
scores = cross_val_score(model, X_test, y_test, cv = kfold)
print("교차 검증 점수 :\n{}".format(scores))

교차 검증 점수 :
[0.56265126 0.63132672 0.68587837 0.59066434 0.6743726 ]